### ISSUE TITLE
Is there any way of contacting you ?

### ISSUE THREAD

**Issue by aseiis** [t-karcher/ClickableMap#1]
Hello !
Sadly, neither GodotQ&A nor GitHub have a private message feature. The template you uploaded here on this repository have helped me a lot for my project and I have some questions to ask you, so if we could find a way to communicate it will be awesome. My email for game development purpose is edesse at protonmail dot com, if needed. 

Best regards

**Comment by t-karcher** [comment]
You've got mail. :-)
