### ISSUE TITLE
Error when running godot 4

### ISSUE THREAD

**Issue by mkinney** [t-karcher/ClickableMap#2]
Getting this error "Error at (376,17): Cannot assign a new value to a constant."

after importing into godot 4 and trying to run:

<img width="1406" alt="Screen Shot 2023-06-08 at 12 29 37 PM" src="https://github.com/t-karcher/ClickableMap/assets/2219838/48d97929-75ee-4f93-9a8c-156993262b95">

**Comment by t-karcher** [comment]
Thanks for the report! This part of the code was not written by me, but is part of the Delaunator library mentioned in the credits. But I'll look into it anyway in the next days and am confident I can fix it.

**Comment by mkinney** [comment]
That's be wonderful. Thanks for sharing this code.

You're awesome! :-D

**Comment by t-karcher** [comment]
Ok, this was even easier than expected: It's working now with Godot 4.0 (but not with 3.x any longer).
